## Day 2 Homework
#Geometry Analysis Hw Solution

measure  distances between atoms

In [2]:
import numpy
import os

# you know you need these bc you need to construct a file path using  os.path.join, and measuring distances means square root uses a numpy function

In [3]:
#open the file os.path.join('folder name','file')
file_location = os.path.join('data','water.xyz')
print(file_location)
#check to see if you have the right folder

data\water.xyz


In [5]:
#read information  in the file, readlines means that pulling info from lists, gennumpy is for tabular information 
#since this file is tabular, choose tabular  (can choose both, but code would look different)
#(file name, delimiter)
#coordinates are floats, words are strings means its UNICODE
#this didnt work without skip, makes all rows have 4 colums 
xyz_file = numpy.genfromtxt(fname=file_location,dtype='unicode', skip_header=2)

In [6]:
print(xyz_file)
#symbols are strings and numbers are floats,  so separate them by taking slices


[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [7]:
symbols = xyz_file[:,0]
#all rows, zeroth column
coordinates = xyz_file[:,1:]
#all rows, 1st thru end column 

print(symbols)
print(coordinates)

#the numbers  have quotes, python thinks theyre strings so you have to recast them into floats 


['O' 'H1' 'H2']
[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [8]:
coordinates = coordinates.astype(numpy.float)

#recasting

In [9]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


#measure distance between these atoms 

$$ distance = \sqrt{(x1-x2)^2 + (y1-y2)^2 + (z1-z2)^2} $$

#text in between $$ will render as  equations


In [19]:
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
       # print(F'Atom 1 is {num1}')
        #print(F'Atom 2 is {num2}')
        if num1<num2:
            x_distance = coordinates[num1,0]-coordinates[num2,0]
            y_distance = coordinates[num1,1]-coordinates[num2,1]
            z_distance = coordinates[num1,2]-coordinates[num2,2]
            #num1  means  atom 1
            distance_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                #only prints if less than 1.5
                print(F'{symbols[num1]} to {symbols[num2]}  :  {distance_12: .3f}')
                    #remember that .3f means to three decimal places 
                    # make a rule that you only wanna print if its less than 1.5 angstroms


O to H1  :   0.969
O to H2  :   0.969


In [ ]:
import numpy
import os
file_location = os.path.join('data','water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location,dtype='unicode', skip_header=2)
symbols = xyz_file[:,0]
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(numpy.float)
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
       # print(F'Atom 1 is {num1}')
        #print(F'Atom 2 is {num2}')
        if num1<num2:
            x_distance = coordinates[num1,0]-coordinates[num2,0]
            y_distance = coordinates[num1,1]-coordinates[num2,1]
            z_distance = coordinates[num1,2]-coordinates[num2,2]
            #num1  means  atom 1
            distance_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                #only prints if less than 1.5
                print(F'{symbols[num1]} to {symbols[num2]}  :  {distance_12: .3f}')